# -*- coding: utf-8 -*-
"""Hijri Events"""

EVENTS = {
    "1": {'9': [{'description': 'تاسوعای حسینی', 'is_holiday': True}],
          '10': [{'description': 'عاشورای حسینی', 'is_holiday': True}],
          '12': [{'description': 'شهادت  امام زین العابدین علیه السلام', 'is_holiday': False}]},
    "2": {'20': [{'description': 'اربعین حسینی', 'is_holiday': True}],
          '28': [{'description': 'رحلت  رسول اکرم؛شهادت امام حسن مجتبی علیه السلام', 'is_holiday': True}],
          '30': [{'description': 'شهادت امام رضا علیه السلام', 'is_holiday': True}]},
    "3": {'1': [{'description': 'هجرت پیامبر اکرم از مکه به مدینه', 'is_holiday': False}],
          '8': [{'description': 'شهادت امام حسن عسکری علیه السلام', 'is_holiday': True}],
          '12': [{'description': 'میلاد رسول اکرم به روایت اهل سنت', 'is_holiday': False}],
          '17': [{'description': 'میلاد رسول اکرم و امام جعفر صادق علیه السلام', 'is_holiday': True}]},
    "4": {'8': [{'description': 'ولادت امام حسن عسکری علیه السلام', 'is_holiday': False}],
          '10': [{'description': 'وفات حضرت معصومه سلام الله علیها', 'is_holiday': False}]},
    "5": {'5': [{'description': 'ولادت حضرت زینب سلام الله علیها و روز پرستار و بهورز', 'is_holiday': False}]},
    "6": {'3': [{'description': 'شهادت حضرت فاطمه زهرا سلام الله علیها', 'is_holiday': True}],
          '20': [{'description': 'ولادت حضرت فاطمه زهرا سلام الله علیها و روز مادر', 'is_holiday': False}]},
    "7": {'1': [{'description': 'ولادت  امام محمد باقر علیه السلام', 'is_holiday': False}],
          '3': [{'description': 'شهادت امام علی النقی الهادی علیه السلام', 'is_holiday': False}],
          '10': [{'description': 'ولادت امام محمد تقی علیه السلام', 'is_holiday': False}],
          '13': [{'description': 'ولادت امام علی علیه السلام و روز پدر', 'is_holiday': True}],
          '15': [{'description': 'وفات حضرت زینب سلام الله علیها', 'is_holiday': False}],
          '25': [{'description': 'شهادت امام موسی کاظم علیه السلام', 'is_holiday': False}],
          '27': [{'description': 'مبعث رسول اکرم (ص)', 'is_holiday': True}]},
    "8": {'3': [{'description': 'ولادت سالار شهیدان، امام حسین علیه السلام و روز پاسدار', 'is_holiday': False}],
          '4': [{'description': 'ولادت ابوالفضل العباس علیه السلام و روز جانباز', 'is_holiday': False}],
          '5': [{'description': 'ولادت امام زین العابدین علیه السلام', 'is_holiday': False}],
          '11': [{'description': 'ولادت علی اکبر علیه السلام و روز جوان', 'is_holiday': False}],
          '15': [{'description': 'ولادت حضرت قائم عجل الله تعالی فرجه و جشن نیمه شعبان', 'is_holiday': True}]},
    "9": {'15': [{'description': 'ولادت امام حسن مجتبی علیه السلام', 'is_holiday': False}],
          '18': [{'description': 'شب قدر', 'is_holiday': False}],
          '19': [{'description': 'ضربت خوردن حضرت علی علیه السلام', 'is_holiday': False}],
          '21': [{'description': 'شهادت حضرت علی علیه السلام', 'is_holiday': True}],
          '22': [{'description': 'شب قدر', 'is_holiday': False}]},
    "10": {'1': [{'description': 'عید سعید فطر', 'is_holiday': True}],
           '2': [{'description': 'تعطیل به مناسبت عید سعید فطر', 'is_holiday': True}],
           '25': [{'description': 'شهادت امام جعفر صادق علیه السلام', 'is_holiday': True}]},
    "11": {'1': [{'description': 'ولادت حضرت معصومه سلام الله علیها و روز دختران', 'is_holiday': False}],
           '11': [{'description': 'ولادت امام  رضا علیه السلام', 'is_holiday': False}]},
    "12": {'7': [{'description': 'شهادت امام محمد باقر علیه السلام', 'is_holiday': False}],
           '9': [{'description': 'روز عرفه', 'is_holiday': False}],
           '10': [{'description': 'عید سعید قربان', 'is_holiday': True}],
           '15': [{'description': 'ولادت امام علی النقی الهادی علیه السلام', 'is_holiday': False}],
           '18': [{'description': 'عید سعید غدیر خم', 'is_holiday': True}],
           '20': [{'description': 'ولادت امام موسی کاظم علیه السلام', 'is_holiday': False}]}


}

