# -*- coding: utf-8 -*-
"""Jalali Events."""

EVENTS = {
    # فروردین
    "1": {
        '1': [{'description': 'جشن نوروز/جشن سال نو', 'is_holiday': True}],
        '2': [{'description': 'عید نوروز', 'is_holiday': True},
              {'description': 'آغاز عملیات فتح‌المبین', 'is_holiday': False}],
        '3': [{'description': 'عید نوروز', 'is_holiday': True}],
        '4': [{'description': 'عید نوروز', 'is_holiday': True},
              {'description': 'درگذشت اسماعیل ادیب خوانساری موسیقیدان ایرانی', 'is_holiday': False}],
        '6': [{'description': 'روز امید، روز شادباش نویسی', 'is_holiday': False},
              {'description': 'زادروز آشو زرتشت، اَبَراِنسان بزرگ تاریخ', 'is_holiday': False}],
        '7': [{'description': 'روز هنرهای نمایشی', 'is_holiday': False}],
        '10': [{'description': 'جشن آبانگاه', 'is_holiday': False}],
        '12': [{'description': 'روز جمهوری اسلامی', 'is_holiday': True}],
        '13': [{'description': 'جشن سیزده به در', 'is_holiday': True},
               {'description': 'درگذشت علی‌اکبر صنعتی نقاش و مجسمه‌ساز ایرانی', 'is_holiday': False},
               {'description': 'روز طبیعت', 'is_holiday': True}],
        '14': [{'description': 'زادروز ابوالحسن صبا موسیقیدان، آهنگساز و نوازندهٔ سرشناس ایرانی', 'is_holiday': False}],
        '15': [{'description': 'درگذشت پروین اعتصامی', 'is_holiday': False},
               {'description': 'روز ذخایر ژنتیکی و زیستی', 'is_holiday': False}],
        '17': [{'description': 'سروش روز، جشن سروشگان', 'is_holiday': False}],
        '18': [{'description': 'روز سلامتی', 'is_holiday': False}],
        '19': [{'description': 'فروردین روز، جشن فروردینگان', 'is_holiday': False}],
        '20': [{'description': 'روز ملی فناوری هسته‌ای', 'is_holiday': False},
               {'description': 'روز هنر انقلاب اسلامی', 'is_holiday': False},
               {'description': 'شهادت سید مرتضی آوینی', 'is_holiday': False}],
        '21': [{'description': 'شهادت امیر سپهبد علی صیاد شیرازی', 'is_holiday': False},
               {'description': 'تأسیس بنیاد مسکن انقلاب اسلامی', 'is_holiday': False}],
        '23': [{'description': 'روز دندانپزشک', 'is_holiday': False}],
        '25': [{'description': 'روز بزرگداشت عطار نیشابوری', 'is_holiday': False}],
        '29': [{'description': 'روز ارتش جمهوری اسلامی ایران', 'is_holiday': False}],
        '30': [{'description': 'روز علوم آزمایشگاهی، زاد‌روز حکیم سید اسماعیل جرجانی', 'is_holiday': False}],
        '31': [{'description': 'روز گندم و نان', 'is_holiday': False}]
    },
    # اردیبهشت
    "2": {
        '1': [{'description': 'روز بزرگداشت سعدی', 'is_holiday': False},
              {'description': 'درگذشت سهراب سپهری شاعر و نقاش ایرانی', 'is_holiday': False},
              {'description': 'روز نثر فارسی', 'is_holiday': False},
              {'description': 'روز شهدای ورزشکار', 'is_holiday': False}],
        '2': [{'description': 'زادروز قیصر امین‌پور نویسنده، مدرس دانشگاه و شاعر معاصرایرانی', 'is_holiday': False},
              {'description': 'زادروز یاور همدانی، شاعر و نویسنده و پژوهشگر ایرانی', 'is_holiday': False},
              {'description': 'تأسیس سپاه پاسداران انقلاب اسلامی', 'is_holiday': False},
              {'description': 'سالروز اعلام انقلاب فرهنگی', 'is_holiday': False},
              ],
        '3': [{'description': 'روز بزرگداشت شیخ بهایی', 'is_holiday': False},
              {'description': 'روزملی کارآفرینی', 'is_holiday': False},
              {'description': 'روز معماری', 'is_holiday': False},
              {'description': 'شهادت امیر سپهبد قرنی', 'is_holiday': False}],
        '4': [{'description': 'آغاز به کار نخستین فرستنده عمومی رادیویی در ایران به نام «رادیو تهران»', 'is_holiday': False}],
        '5': [{'description': 'زادروز جلیل ضیاءپور، پدر نقاشی مدرن ایران', 'is_holiday': False},
              {'description': 'شکست حمله نظامی آمریکا به ایران در طبس', 'is_holiday': False}],
        '6': [{'description': 'فاجعه‌ی انفجارِ بندر عباس [ 1404 خورشیدی]', 'is_holiday': False}],
        '7': [{'description': 'روز ایمنی حمل و نقل', 'is_holiday': False}],
        '8': [{'description': 'زادروز سیمین دانشور نویسنده و مترجم ایرانی', 'is_holiday': False}],
        '9': [{'description': 'روز ملی روانشناس و مشاور', 'is_holiday': False},
              {'description': 'درگذشت ذبیح‌الله صفا، پژوهشگر، مترجم و استاد ممتاز دانشگاه تهران', 'is_holiday': False},
              {'description': 'روز شوراها', 'is_holiday': False}],
        '10': [{'description': 'جشن چهلم نوروز', 'is_holiday': False},
               {'description': 'روز ملی خلیج فارس', 'is_holiday': False},
               {'description': 'آغاز عملیات بیت‌المقدس', 'is_holiday': False}],
        '11': [{'description': 'انتشار نخستین روزنامه در ایران به نام «کاغذ اخبار» توسط «میرزا صالح شیرازی»', 'is_holiday': False}],
        '12': [{'description': 'روز معلم', 'is_holiday': False},
               {'description': 'درگذشت محمدرضا لطفی، نوازندهٔ برجسته و سرشناس تار، سه‌تار و ردیف‌دان، موسیقی‌دان و آهنگساز', 'is_holiday': False},
               {'description': 'شهادت استاد مرتضی مطهری', 'is_holiday': False}],
        '14': [{'description': 'زادروزخواجه عبدالله انصاری، ادیب، عارف و اندیشمند ایرانی', 'is_holiday': False}],
        '15': [{'description': 'جشن میانه بهار/جشن بهاربد', 'is_holiday': False},
               {'description': 'روز شیراز', 'is_holiday': False},
               {'description': 'زادروز غلامحسین بنان، خوانندهٔ ایرانی', 'is_holiday': False},
               {'description': 'بزرگداشت شیخ صدوق', 'is_holiday': False},
               {'description': 'روز صنعت بتن آماده', 'is_holiday': False},
               {'description': 'روز صنعت تهویه مطبوع', 'is_holiday': False}],
        '16': [{'description': 'درگذشت حسین منزوی شاعر نامدار ایرانی', 'is_holiday': False}],
        '18': [{'description': 'روز بیماری‌های خاص و صعب‌العلاج', 'is_holiday': False}],
        '19': [{'description': 'بزرگداشت شیخ کلینی', 'is_holiday': False},
               {'description': 'روز اسناد ملی و میراث مکتوب', 'is_holiday': False}],
        '20': [{'description': 'روز گل محمدی و گلاب', 'is_holiday': False}],
        '21': [{'description': 'زادروز فرنگیس یگانگی بنیان‌گذار و نخستین مدیرعامل سازمان صنایع دستی ایران', 'is_holiday': False}],
        '22': [{'description': 'زادروز مریم میرزاخانی ریاضیدان ایرانی، اولین زن برندهٔ جایزه فیلدز', 'is_holiday': False},
               {'description': 'روز جهانی زن در ریاضیات (به افتخار روز تولد مریم میرزاخانی)', 'is_holiday': False},
               {'description': 'روز مشاغل خانگی و تولید خانواده‌محور', 'is_holiday': False}],
        '24': [{'description': 'زادروز پرویز مشکاتیان آهنگساز، موسیقی‌دان و نوازندهٔ سنتور', 'is_holiday': False},
               {'description': 'لغو امتیاز تنباکو به فتوای آیت‌الله میرزا حسن شیرازی', 'is_holiday': False}],
        '25': [{'description': 'روز بزرگداشت فردوسی', 'is_holiday': False},
               {'description': 'روز پاسداشت زبان فارسی', 'is_holiday': False}],
        '27': [{'description': 'روز ارتباطات و روابط عمومی', 'is_holiday': False}],
        '28': [{'description': 'روز بزرگداشت حکیم عمر خیام', 'is_holiday': False}],
        '30': [{'description': 'روز ملی جمعیت', 'is_holiday': False},
               {'description': 'روز شهدای خدمت', 'is_holiday': False}],
        '31': [{'description': 'روز اهدای عضو، اهدای زندگی', 'is_holiday': False},
               {'description': 'روز بوم‌گردی', 'is_holiday': False}]
        
    },
    # خرداد
    "3": {
        '1': [{'description': 'روز بهره وری و بهینه سازی مصرف', 'is_holiday': False},
              {'description': 'روز بزرگداشت ملاصدرا', 'is_holiday': False},
              {'description': 'زادروز جلیل شهناز، از سرشناس‌ترین نوازندگان تار و سه تار سدهٔ اخیر در ایران', 'is_holiday': False}],
        '2': [{'description': 'فروریختن ساختمان متروپل در آبادان', 'is_holiday': False}],
        '3': [{'description': 'فتح خرمشهر در عملیات بیت المقدس و روز مقاومت، ایثار و پیروزی', 'is_holiday': False}],
        '4': [{'description': 'روز دزفول، روز مقاومت و پایداری', 'is_holiday': False}],
        '5': [{'description': 'درگذشت هوشنگ سیحون معمار، طراح، نقاش و مجسمه‌ساز ایرانی', 'is_holiday': False},
              {'description': 'روز نسیم مهر (حمایت از خانواده زندانیان)', 'is_holiday': False}],
        '6': [{'description': 'خرداد روز، جشن خردادگان', 'is_holiday': False}],
        '7': [{'description': 'افتتاح اولین دوره مجلس شورای اسلامی', 'is_holiday': False},
              {'description': 'روز نقشه‌برداری', 'is_holiday': False}],
        '8': [{'description': 'روز مشاور املاک', 'is_holiday': False}],
        '14': [{'description': 'رحلت حضرت امام خمینی', 'is_holiday': True},
               {'description': 'انتخاب آیت‌الله خامنه‌ای به رهبری', 'is_holiday': False}],
        '15': [{'description': 'قیام 15 خرداد', 'is_holiday': True},
               {'description': 'درگذشت شیخ بهایی دانشمند عصر صفوی', 'is_holiday': False}],
        '20': [{'description': 'روز صنایع دستی', 'is_holiday': False},
               {'description': 'روز ملی فرش', 'is_holiday': False},
               {'description': 'شهادت آیت‌الله سعیدی', 'is_holiday': False}],
        '23': [{'description': 'روز شهدای اقتدار و اتحاد ملی', 'is_holiday': False}],
        '25': [{'description': 'روز ملی گل وگیاه', 'is_holiday': False}],
        '26': [{'description': 'زادروز توران میرهادی استاد ادبیات کودک، نویسنده و کارشناس آموزش و پرورش و شخصیت برجسته فرهنگی', 'is_holiday': False},
               {'description': 'شهادت بخارایی، امانی، صفار هرندی و نیک‌نژاد', 'is_holiday': False}],
        '27': [{'description': 'درگذشت جلیل شهناز، از سرشناس‌ترین نوازندگان تار و سه تار سدهٔ اخیر در ایران', 'is_holiday': False},
               {'description': 'روز جهاد کشاورزی', 'is_holiday': False},
               {'description': 'تشکیل جهاد سازندگی', 'is_holiday': False},],
        '29': [{'description': 'درگذشت دکتر علی شریعتی', 'is_holiday': False}],
        '30': [{'description': 'شهادت زائران حرم رضوی', 'is_holiday': False},
               {'description': 'روز صنعت موتورسیکلت', 'is_holiday': False}],
        '31': [{'description': 'شهادت دکتر مصطفی چمران', 'is_holiday': False},
               {'description': 'سالروز زلزله رودبار و منجیل [1369خورشیدی]', 'is_holiday': False},
               {'description': 'روز بسیج استادان', 'is_holiday': False}],
    },
    # تیر
    "4": {
        '1': [{'description': 'جشن آب پاشونک، جشن آغاز تابستان', 'is_holiday': False},
              {'description': 'درگذشت ابن سینا فیلسوف، پزشک و دانشمند نامدار ایرانی', 'is_holiday': False},
              {'description': 'درگذشت غیاث‌الدین جمشید کاشانی ریاضیدان و اخترشناس ایرانی', 'is_holiday': False},
              {'description': 'روز تبلیغ و اطلاع‌رسانی دینی', 'is_holiday': False},
              {'description': 'تأسیس سازمان تبلیغات اسلامی', 'is_holiday': False},
              {'description': 'روز اصناف', 'is_holiday': False}],
        '3': [{'description': 'درگذشت ابن سینا پزشک و فیلسوف ایرانی', 'is_holiday': False}],
        '5': [{'description': 'درگذشت میرزا احمد آشتیانی فقیه، فیلسوف شیعی ایرانی', 'is_holiday': False},
              {'description': 'روز صنعت ابزارآلات', 'is_holiday': False}],
        '6': [{'description': 'روز عینک‌سازی و بینایی‌سنجی', 'is_holiday': False}],
        '7': [{'description': 'انفجار دفتر حزب جمهوری اسلامی و شهادت دکتر بهشتی و 72 نفر از اعضای حزب', 'is_holiday': False},
              {'description': 'روز قوه قضاییه', 'is_holiday': False},
              {'description': 'بمباران شیمیایی شهر سردشت', 'is_holiday': False}],
        '8': [{'description': 'روز مبارزه با سلاح های شیمیایی و میکروبی', 'is_holiday': False}],
        '10': [{'description': 'روز صنعت و معدن', 'is_holiday': False},
               {'description': 'زادروز بابک خرمدین، سپه‌سالار دلاور ایران', 'is_holiday': False},
               {'description': 'روز بزرگداشت صائب تبریزی', 'is_holiday': False},
               {'description': 'روز دیپلماسی فرهنگی و تعامل با جهان', 'is_holiday': False},
               {'description': 'آزادسازی شهر مهران', 'is_holiday': False}],
        '11': [{'description': 'درگذشت کیخسرو شاهرخ، بنیانگذار آرامگاه فردوسی و کتابخانه مجلس شورای ملی و مدیر عامل شرکت سهامی تلفن', 'is_holiday': False},
               {'description': 'شهادت آیت‌الله صدوقی', 'is_holiday': False}],
        '12': [{'description': 'شلیک به پرواز 655 ایران ایر توسط ناو وینسنس [ 1367 خورشیدی ]', 'is_holiday': False},
               {'description': 'روز افشای حقوق بشر آمریکایی', 'is_holiday': False},
               {'description': 'بزرگداشت علامه امینی', 'is_holiday': False},
               {'description': 'حمایت از تولید ملی و مبارزه با قاچاق کالا', 'is_holiday': False},
               {'description': 'روز خیاط، صنعت نساجی و پوشاک', 'is_holiday': False}],
        '13': [{'description': 'تیر روز، جشن تیرگان', 'is_holiday': False},
               {'description': 'زادروز فرشید مثقالی مجسمه‌ساز، گرافیست و تصویرگر کتاب کودک، اولین و تنها ایرانی برنده جایزه هانس کریستیان آندرسن', 'is_holiday': False},
               {'description': 'جشن تیرگان، بزرگداشت کمان کشیدن جان فدای ایران، آرش کمانگیر بر فراز البرز', 'is_holiday': False}],
        '14': [{'description': 'روز قلم', 'is_holiday': False},
               {'description': 'روز شهرداری و دهیاری', 'is_holiday': False}],
        '15': [{'description': 'جشن خام خواری', 'is_holiday': False}],
        '16': [{'description': 'روز مالیات', 'is_holiday': False}],
        '17': [{'description': 'درگذشت کارو لوکس، از پژوهشگران به‌نام سیستم‌های هوشمند در ایران، «پدر علم رباتیک ایران»', 'is_holiday': False}],
        '18': [{'description': 'روز ادبیات کودکان و نوجوانان', 'is_holiday': False},
               {'description': 'کشف توطئه آمریکایی در پایگاه هوایی شهید نوژه', 'is_holiday': False},
               {'description': 'روز صنعت قیر و آسفالت', 'is_holiday': False}],
        '21': [{'description': 'درگذشت مریم میرزاخانی، ریاضیدان ایرانی و اولین زن برنده مدال فیلدز', 'is_holiday': False},
               {'description': 'روز عفاف و حجاب', 'is_holiday': False},
               {'description': 'حمله به مسجد گوهرشاد و کشتار مردم به دست رضاخان', 'is_holiday': False}],
        '22': [{'description': 'زادروز عباس زریاب خویی، مترجم، تاریخ‌دان و کتاب‌شناس ایرانی', 'is_holiday': False},
               {'description': 'درگذشت مهدی حمیدی شیرازی، ادیب، شاعر، مترجم و منتقد ایرانی', 'is_holiday': False},
               {'description': 'زادروز محمد خوارزمی، ریاضیدان و فیلسوف ایرانی و روز ملی فناوری اطلاعات', 'is_holiday': False}],
        '23': [{'description': 'روز گفتگو و تعامل سازنده با جهان', 'is_holiday': False},
               {'description': 'گشایش نخستین مجلس خبرگان رهبری', 'is_holiday': False}],      
        '25': [{'description': 'روز بهزیستی و تامین اجتماعی', 'is_holiday': False}],
        '26': [{'description': 'تأسیس نهاد شورای نگهبان', 'is_holiday': False}],
        '27': [{'description': 'اعلام پذیرش قطعنامه 598 شورای امنیت از سوی ایران [ 1367 خورشیدی ]', 'is_holiday': False}],
        '30': [{'description': 'بزرگداشت آیت‌الله کاشانی', 'is_holiday': False},
               {'description': 'روز خلبان', 'is_holiday': False}]
    },
    # مرداد
    "5": {
        '4': [{'description': 'افتتاح بزرگترین پالایشگاه نفت سنگین جهان در بندرعباس', 'is_holiday': False}],
        '7': [{'description': 'اَمرداد روز، جشن  اَمردادگان', 'is_holiday': False}],
        '8': [{'description': 'روز بزرگداشت شیخ شهاب الدین سهروردی', 'is_holiday': False}],
        '9': [{'description': 'سالروز اهدای خون در ایران', 'is_holiday': False}],
        '10': [{'description': 'جشن چله تابستان', 'is_holiday': False}],
        '14': [{'description': 'سالروز صدور فرمان مشروطیت', 'is_holiday': False},
               {'description': 'برگزاری اولین کنکور در ایران', 'is_holiday': False}],
        '17': [{'description': 'روز خبرنگار', 'is_holiday': False}],
        '26': [{'description': 'سالروز ورود آزادگانِ سرافراز به وطن', 'is_holiday': False}],
        '28': [{'description': 'سالروز وقایع 28 مرداد پس از برکناری محمد مصدق', 'is_holiday': False},
               {'description': 'سالروز فاجعه آتش زدن سینما رکس آبادان', 'is_holiday': False}],
        '30': [{'description': 'روز پزشک', 'is_holiday': False},
               {'description': 'زادروز ابن سینا پزشک و شاعر و از مشهورترین و تاثیرگذارترینِ فیلسوفان و دانشمندان ایران‌زمین', 'is_holiday': False}],
    },
    # شهریور
    "6": {
        '1': [{'description': 'روز بزرگداشت ابوعلی سینا و روز پزشک', 'is_holiday': False}],
        '2': [{'description': 'آغاز هفته دولت', 'is_holiday': False}],
        '4': [{'description': 'زادروز کوروش بزرگ', 'is_holiday': False},
              {'description': 'شهریور روز، جشن شهریورگان', 'is_holiday': False}],
        '5': [{'description': 'روز بزرگداشت محمدبن زکریای رازی و روز داروساز', 'is_holiday': False}],
        '8': [{'description': 'انفجار در دفتر نخست‌وزیری جمهوری اسلامی ایران، روز مبارزه با تروریسم', 'is_holiday': False},
              {'description': 'درگذشت علامه حلی از علمای شیعه قرن هشتم قمری', 'is_holiday': False}],
        '10': [{'description': 'امضای معاهده تقسیم ایران بین روسیه و انگلیس', 'is_holiday': False}],
        '11': [{'description': 'روزصنعت چاپ', 'is_holiday': False},
               {'description': 'وقوع زلزله بویین زهرا و مرگ بیش از 25 هزار نفر', 'is_holiday': False},
               {'description': 'درگذشت محمود حسابی فیزیکدان، سناتور، وزیر آموزش و پرورش و بنیانگذار دانشگاهی در ایران', 'is_holiday': False}],
        '12': [{'description': 'سالروز شهادت رئیسعلی دلواری، سردار بزرگ میهن و فرمانده قیام جنوب علیه اشغالگران انگلیسی', 'is_holiday': False}],
        '13': [{'description': 'روز بزرگداشت ابوریحان بیرونی', 'is_holiday': False}],
        '14': [{'description': 'زادروز ابوریحان بیرونی دانشمند بزرگ، ریاضی‌دان، ستاره‌شناس، تقویم‌شناس، انسان‌شناس، هندشناس و تاریخ‌نگار بزرگ ایرانی', 'is_holiday': False}],
        '17': [{'description': 'قیام 17 شهریور', 'is_holiday': False},
               {'description': 'درگذشت جلال آل احمد روشنفکر دینی، نویسنده و مترجم ایرانی و همسر سیمین دانشور', 'is_holiday': False}],
        '18': [{'description': 'درگذشت علینقی وزیری، موسیقی‌دان و آهنگ‌ساز ایرانی', 'is_holiday': False}],
        '19': [{'description': 'درگذشت آیت الله سید محمود طالقانی', 'is_holiday': False}],
        '20': [{'description': 'درگذشت محمدعلی جناح بنیانگذار کشور پاکستان', 'is_holiday': False}],
        '21': [{'description': 'روز سینما', 'is_holiday': False}],
        '22': [{'description': 'کشته شدن شیخ محمد خیابانی از فعالان سیاسی در دوره انقلاب مشروطه ایران', 'is_holiday': False}],
        '23': [{'description': 'سفر انوشه انصاری به‌ عنوان اولین زن گردشگر فضایی به دور مدار زمین', 'is_holiday': False},
               {'description': 'درگذشت هانیبال الخاص، نقاش و مجسمه ساز ایرانی', 'is_holiday': False}],
        '24': [{'description': 'اعدام صادق قطب‌زاده، وزیر سابق امور خارجه جمهوری اسلامی ایران', 'is_holiday': False},
               {'description': 'درگذشت عبدالحسین زرین‌کوب خوانساری، ادیب، تاریخ‌نگار و منتقد ادبی برجسته ایران', 'is_holiday': False}],
        '25': [{'description': 'زمین لرزه طبس به قدرت 7/8 ریشتر', 'is_holiday': False},
               {'description': 'برگزاری انتخابات دوره نخست مجلس شورای ملی', 'is_holiday': False}],
        '26': [{'description': 'لغو عهدنامه ۱۹۷۵ الجزایر توسط صدام حسین', 'is_holiday': False},
               {'description': 'سالروز ترور میکونوس در شهر برلین', 'is_holiday': False}],
        '27': [{'description': 'روز شعر و ادب پارسی و  روز بزرگداشت استاد شهریار', 'is_holiday': False},
               {'description': 'درگذشت سید محمدحسین شهریار شاعر نامدار ایرانی', 'is_holiday': False}],
        '30': [{'description': 'زادروز فریدون مشیری  شاعر ایرانی', 'is_holiday': False},
               {'description': 'درگذشت پرویز مشکاتیان موسیقی‌دان و نوازنده ایرانی', 'is_holiday': False}],
        '31': [{'description': 'آغاز هفته دفاع مقدس', 'is_holiday': False},
               {'description': 'زادروز پرویز یاحقی، نوازنده‌‌ی چیره‌دست ویلون؛ موسیقیدان و آهنگساز ایرانی', 'is_holiday': False}],
    },
    # مهر
    "7": {
        '1': [{'description': 'زادروز محمدرضا شجریان خواننده، موسیقی‌دان و خوشنویس ایرانی', 'is_holiday': False},
              {'description': 'زادروز حسین منزوی شاعر ایرانی', 'is_holiday': False},
              {'description': 'آغاز حمله مغول به ایران در پاییز 598 خورشیدی', 'is_holiday': False}],
        '3': [{'description': 'انحلال حزب رستاخیز', 'is_holiday': False}],
        '4': [{'description': 'تأسیس باشگاه فوتبال استقلال (تاج)', 'is_holiday': False},
              {'description': 'روز گرامیداشت سربازان وطن', 'is_holiday': False}],
        '6': [{'description': 'اعدام سید مهدی هاشمی به جرم توطئه علیه نظام و بانی فاش ساختن رسوایی ایران-کنترا', 'is_holiday': False}],
        '7': [{'description': 'روز آتش نشانی و ایمنی', 'is_holiday': False},
              {'description': 'سقوط هواپیمای حامل جمعی از فرماندهان جنگ (کلاهدوز، نامجو، فلاحی، فکوری، جهان آرا) در سال 1360', 'is_holiday': False},
              {'description': 'روز بزرگداشت شمس تبریزی', 'is_holiday': False}],
        '8': [{'description': 'روزبزرگداشت مولوی', 'is_holiday': False}],
        '9': [{'description': 'پیروزی اسکندر مقدونی در نبرد گوگمل و شکست شاه ایران، داریوش سوم و انقراض امپراطوری بزرگ هخامنشی', 'is_holiday': False},
              {'description': 'اعدام خسرو قشقایی به اتهام مبارزه مسلحانه علیه جمهوری اسلامی در فیروزآباد فارس', 'is_holiday': False},
              {'description': 'قتل عبدالحسین تیمورتاش، دولت‌مرد ایرانی در دوره‌های قاجار و پهلوی، در زندان قصر تهران', 'is_holiday': False}],
        '10': [{'description': 'مهر روز، جشن مهرگان', 'is_holiday': False},
               {'description': 'تأسیس حزب توده ایران', 'is_holiday': False}],
        '14': [{'description': 'روز دامپزشکی', 'is_holiday': False}],
        '16': [{'description': 'روز ملی کودک', 'is_holiday': False}],
        '20': [{'description': 'روز بزرگداشت حافظ', 'is_holiday': False}],
        '21': [{'description': 'روز پیروزی کاوه و فریدون بر ضحاک', 'is_holiday': False}],
        '26': [{'description': 'روز تربیت بدنی و ورزش', 'is_holiday': False},
               {'description': 'زادروز ابراهیم گلستان کارگردان، نخستین برندهٔ یک جایزه بین‌المللی برای سینمای ایران', 'is_holiday': False}],
        '28': [{'description': 'اعدام سرهنگ عزت‌الله سیامک به همراه 9 تن دیگر به عنوان اولین گروه از افسران حزب توده بعد از ماجرای 28 مرداد', 'is_holiday': False},
               {'description': 'زادروز ستارخان ملقب به سردار ملی و از سرداران جنبش مشروطه ایران', 'is_holiday': False}],
        '29': [{'description': 'روز ملی کوهنورد', 'is_holiday': False}],
    },
    # آبان
    "8": {
        '1': [{'description': 'روز آمار و برنامه ریزی', 'is_holiday': False},
              {'description': 'آغاز کار نخستین فرستنده تلویزیون دولتی ایران، به نام «شبکه ملی»', 'is_holiday': False},
              {'description': 'روز بزرگداشت ابوالفضل بیهقی، تاریخ‌نگار و نویسنده ایرانی', 'is_holiday': False}],
        '3': [{'description': 'درگذشت فریدون مشیری شاعر ایرانی', 'is_holiday': False}],
        '6': [{'description': 'هجرت محمد (ص) از مکه به مدینه و انتخاب این روز به عنوان مبدأ تاریخ مسلمانان در دو تقویم هجری شمسی و هجری قمری', 'is_holiday': False}],
        '7': [{'description': 'سالروز ورود کوروش بزرگ به بابل در سال 539 پیش از میلاد', 'is_holiday': False},
              {'description': 'روز کوروش بزرگ: کوروش بزرگ بنیانگذار امپراتوری هخامنشیان در ایران، شهر بابِل، بزرگترین شهر دنیای باستان و مرکز تمدن بابل را فتح کرد.', 'is_holiday': False}],
        '8': [{'description': 'روز نوجوان', 'is_holiday': False},
              {'description': 'زادروز آیدین آغداشلو نقاش، نویسنده، منتقد فیلم و طراح هنرمند ایرانی', 'is_holiday': False}],
        '9': [{'description': 'درگذشت محمد زکریای رازی پزشک، فیلسوف و شیمیدان ایرانی.', 'is_holiday': False}],
        '10': [{'description': 'آبان روز، جشن آبانگان', 'is_holiday': False}],
        '13': [{'description': 'روز دانش آموز', 'is_holiday': False}],
        '14': [{'description': 'روز فرهنگ عمومی', 'is_holiday': False},
               {'description': 'زادروز محمدرضا اسحاقی گرجی، نوازنده و موسیقی‌دان مازندرانی', 'is_holiday': False},
               {'description': 'روز ملّی مازندران', 'is_holiday': False}],
        '15': [{'description': 'جشن میانه پاییز', 'is_holiday': False}],
        '16': [{'description': 'زادروز محمدتقی بهار ملقب به ملک‌الشعرا، شاعر، ادیب، نویسنده و سیاست‌مدار ایرانی', 'is_holiday': False}],
        '18': [{'description': 'روز ملی کیفیت', 'is_holiday': False},
               {'description': 'زادروز محمد اقبال شاعر و فیلسوف بزرگ زبان فارسی', 'is_holiday': False}],
        '21': [{'description': 'زادروز نیما یوشیج پدر شعر نو پارسی', 'is_holiday': False},
               {'description': 'درگذشت هاراطون داویدیان بنیانگذار روانپزشکی درایران', 'is_holiday': False}],
        '23': [{'description': 'درگذشت سعید نفیسی، نویسنده، ادیب، تاریخ‌نگار، مترجم و شاعر ایرانی', 'is_holiday': False}],
        '24': [{'description': 'روز کتاب و کتابخوانی', 'is_holiday': False}],
        '28': [{'description': 'درگذشت ستارخان ملقب به سردار ملی از سرداران جنبش مشروطه ایران', 'is_holiday': False}],
    },
    # آذر
    "9": {
        '1': [{'description': 'آذر جشن', 'is_holiday': False},
              {'description': 'روز صنعت سرب و روی', 'is_holiday': False}],
        '2': [{'description': 'درگذشت غلامحسین درویش معروف به «درویش‌خان»، هنرمند نامی و استاد موسیقی ایرانی اواخر دورهٔ قاجاریه', 'is_holiday': False}],
        '3': [{'description': 'زادروز کیهان کلهر آهنگساز و نوازندهٔ برجسته ایرانی', 'is_holiday': False}],
        '4': [{'description': 'درگذشت جبار باغچه‌بان بنیان‌گذار نخستین کودکستان و نخستین مدرسه ناشنوایان ایران، اولین مؤلف و ناشر کتاب کودک در ایران', 'is_holiday': False},
              {'description': 'روز زیتون', 'is_holiday': False}],
        '5': [{'description': 'روز بسیج مستضعفان', 'is_holiday': False},
              {'description': 'سالروز قیام مردم گرگان', 'is_holiday': False}],
        '7': [{'description': 'سالروز عملیات مروارید و روز نیروی دریایی', 'is_holiday': False},
              {'description': 'روز نوآوری و فناوری ایران‌ساخت', 'is_holiday': False}],
        '9': [{'description': 'جشن آذرگان، آذر روز', 'is_holiday': False},
              {'description': 'بزرگداشت شیخ مفید', 'is_holiday': False},
              {'description': 'روز جزایر سه‌گانه خلیج فارس (ابوموسی، تنب بزرگ و تنب کوچک)', 'is_holiday': False}],
        '10': [{'description': 'روز مجلس', 'is_holiday': False},
               {'description': 'شهادت آیت‌الله سید حسن مدرس', 'is_holiday': False}],
        '11': [{'description': 'کشته شدن میرزا کوچک خان جنگلی مبارز و رهبر جنبش ملی جنگل', 'is_holiday': False}],
        '12': [{'description': 'رسمی شدن قانون اساسی جمهوری اسلامی ایران', 'is_holiday': False}],
        '13': [{'description': 'روز بیمه', 'is_holiday': False}],
        '15': [{'description': 'روز حسابدار', 'is_holiday': False}],
        '16': [{'description': 'روز دانشجو', 'is_holiday': False},
               {'description': 'کناره گیری رضا شاه از سلطنت به نفع پسرش محمدرضا پهلوی در پی اشغال ایران در جنگ جهانی دوم توسط نیروهای متفقین', 'is_holiday': False}],
        '17': [{'description': 'زادروز داریوش مهرجویی کارگردان، نویسنده و مترجم ایرانی.', 'is_holiday': False}],
        '18': [{'description': 'معرفی عراق به‌عنوان آغازگر جنگ از سوی سازمان ملل', 'is_holiday': False},
               {'description': 'روز سد و نیروگاه برق‌آبی', 'is_holiday': False}],
        '19': [{'description': 'زادروز حیدر رقابی متخلص به هاله از شاعران معاصر اهل ایران', 'is_holiday': False},
               {'description': 'تشکیل شورای عالی انقلاب فرهنگی', 'is_holiday': False}],
        '20': [{'description': 'درگذشت ابوالحسن صدیقی نقاش و مجسمه‌ساز برجستهٔ ایرانی', 'is_holiday': False},
               {'description': 'شهادت آیت‌الله دستغیب', 'is_holiday': False}],
        '21': [{'description': 'زادروز احمد شاملو شاعر و نویسنده و مترجم ایرانی', 'is_holiday': False},
               {'description': 'سالروز نجات آذربایجان', 'is_holiday': False}],
        '22': [{'description': 'روز صنعت مس', 'is_holiday': False}],
        '25': [{'description': 'روز پژوهش و فنآوری', 'is_holiday': False}],
        '26': [{'description': 'روز حمل و نقل', 'is_holiday': False}],
        '27': [{'description': 'شهادت آیت‌الله دکتر محمد مفتح', 'is_holiday': False},
               {'description': 'روز وحدت حوزه و دانشگاه', 'is_holiday': False},
               {'description': 'روز جهان عاری از خشونت و افراط‌گرایی', 'is_holiday': False}],
        '29': [{'description': 'تجلیل از شهید تندگویان', 'is_holiday': False}],
        '30': [{'description': 'جشن شب یلدا، شب چلّه', 'is_holiday': False},
               {'description': 'روز ترویج فرهنگ میهمانی و پیوند با خویشان', 'is_holiday': False}]
    },
    # دی
    "10": {
        '1': [{'description': 'روز میلاد خورشید', 'is_holiday': False},
              {'description': 'روز آرایشگر', 'is_holiday': False}, 
              {'description': 'جشن خرم روز، نخستین جشن دیگان', 'is_holiday': False}],
        '3': [{'description': 'زادروز احمد محمود نویسندهٔ معاصر ایرانی', 'is_holiday': False},
              {'description': 'روز ثبت احوال', 'is_holiday': False}],
        '4': [{'description': 'بزرگداشت رودکی', 'is_holiday': False}],
        '5': [{'description': 'زمین لرزه ی بم [1382 خورشیدی]', 'is_holiday': False},
              {'description': 'سالروز شهادت آشو زرتشت، اَبَراِنسان بزرگ تاریخ', 'is_holiday': False},
              {'description': 'درگذشت اکبر رادی نمایشنامه نویس ایرانی', 'is_holiday': False},
              {'description': 'روز ایمنی در برابر زلزله و کاهش اثرات بلایای طبیعی', 'is_holiday': False},
              {'description': 'سالروز عملیات کربلای 4 [1365 خورشیدی]', 'is_holiday': False}],
        '6': [{'description': 'روز دفاتر اسناد رسمی', 'is_holiday': False}],
        '7': [{'description': 'تشکیل نهضت سوادآموزی', 'is_holiday': False},
              {'description': 'شهادت آیت‌الله حسین غفاری', 'is_holiday': False}],
        '8': [{'description': 'دی به آذر روز، دومین جشن دیگان', 'is_holiday': False},
              {'description': 'زادروز فروغ فرخزاد شاعر ایرانی', 'is_holiday': False},
              {'description': 'روز بزرگداشت یعقوب لیث صفاری (رادمان پورماهک) نخستین پادشاه ایرانی پس از اسلام', 'is_holiday': False},
              {'description': 'روز صنعت پتروشیمی', 'is_holiday': False},
              {'description': 'روز صنعت سیمان', 'is_holiday': False}],
        '9': [{'description': 'اعدام میهن‌پرستان آذری در تبریز توسط قوای اشغالگر روس [1290 خورشیدی]', 'is_holiday': False},
              {'description': 'روز بصیرت', 'is_holiday': False}],
        '10': [{'description': 'زادروز لیلیت تریان مجسمه‌ساز ایرانی، مادر مجسمه‌سازی ایران', 'is_holiday': False}],
        '12': [{'description': 'روز حافظ', 'is_holiday': False},
               {'description': 'روز علوم انسانی اسلامی', 'is_holiday': False}],
        '13': [{'description': 'درگذشت نیما یوشیج پدر شعر نو پارسی', 'is_holiday': False},
               {'description': 'شهادت سردار حاج قاسم سلیمانی [1398 خورشیدی]', 'is_holiday': False},
               {'description': 'روز جهانی مقاومت', 'is_holiday': False}],
        '15': [{'description': 'دی به مهر روز، سومین جشن دیگان', 'is_holiday': False},
               {'description': 'شهادت منصور ستاری از فرماندهان نیروی هوایی ارتش جمهوری اسلامی ایران', 'is_holiday': False}],
        '16': [{'description': 'غرق شدن کشتی سانچی [1396 خورشیدی]', 'is_holiday': False},
               {'description': 'روز شهدای دانشجو', 'is_holiday': False}],
        '17': [{'description': 'اعدام بابک خرمدین به دست معتصم، خلیفه عباسی در سامرا', 'is_holiday': False},
               {'description': 'حادثه کشته شدن 56 تن از تشیع کنندگان در کرمان', 'is_holiday': False},
               {'description': 'بزرگداشت خواجوی کرمانی', 'is_holiday': False},
               {'description': 'روز کرمان', 'is_holiday': False}],
        '18': [{'description': 'شلیک به پرواز 752 هواپیمایی اوکراین [1398 خورشیدی]', 'is_holiday': False}],
        '19': [{'description': 'درگذشت اکبر هاشمی رفسنجانی [1395 خورشیدی]', 'is_holiday': False},
               {'description': 'قیام خونین مردم قم', 'is_holiday': False}],
        '20': [{'description': 'قتل امیرکبیر به دستور ناصرالدین شاه قاجار [1230 خورشیدی]', 'is_holiday': False},
               {'description': 'روز قناد، صنعت شیرینی و شکلات', 'is_holiday': False}],
        '22': [{'description': 'زادروز محسن هشترودی ریاضی‌دان، فیلسوف و شاعر ایرانی.', 'is_holiday': False},
               {'description': 'تشکیل شورای انقلاب', 'is_holiday': False}],
        '23': [{'description': 'دی به دین روز، چهارمین جشن دیگان', 'is_holiday': False}],
        '27': [{'description': 'اجرای توافق نامه‌ی برجام', 'is_holiday': False},
               {'description': 'شهادت نواب صفوی، طهماسبی، برادران واحدی و ذوالقدر', 'is_holiday': False}],
        '29': [{'description': 'روز غزه', 'is_holiday': False},
               {'description': 'روز معاینه فنی خودرو', 'is_holiday': False}],
        '30': [{'description': 'آتش‌سوزی و فروریختن ساختمان پلاسکو [1395 خورشیدی]', 'is_holiday': False}],
    },
    # بهمن
    "11": {
        '1': [{'description': 'زادروز فردوسی', 'is_holiday': False},
              {'description': 'روز بزرگداشت خاقانی شروانی', 'is_holiday': False}],
        '2': [{'description': 'بهمن روز، جشن بهمنگان', 'is_holiday': False}],
        '5': [{'description': 'جشن نوسره', 'is_holiday': False}],
        '6': [{'description': 'بزرگداشت صفی‌الدین اُرمَوی و روز موسیقی ایرانی', 'is_holiday': False},
              {'description': 'سالروز حماسه مردم آمل', 'is_holiday': False}],
        '10': [{'description': 'جشن سده، گرامیداشتِ کشف آتش به دستِ هوشنگ شاه', 'is_holiday': False}],
        '11': [{'description': 'روز ویراستار', 'is_holiday': False}],
        '12': [{'description': 'بازگشت امام خمینی (ره) به ایران', 'is_holiday': False},
               {'description': 'آغاز دهه فجر انقلاب اسلامی', 'is_holiday': False}],
        '14': [{'description': 'روز فناوری فضایی', 'is_holiday': False}],
        '15': [{'description': 'جشن میانه زمستان', 'is_holiday': False}],
        '19': [{'description': 'روز نیروی هوایی', 'is_holiday': False}],
        '20': [{'description': 'روز چهارمحال و بختیاری', 'is_holiday': False}],
        '21': [{'description': 'شکسته شدن حکومت نظامی به فرمان امام خمینی', 'is_holiday': False}],
        '22': [{'description': 'پیروزی انقلاب اسلامی', 'is_holiday': True}],
        '29': [{'description': 'جشن سپندارمذگان و روز عشق', 'is_holiday': False},
               {'description': 'فاجعه انفجار قطار نیشابور [1382 خورشیدی]', 'is_holiday': False},
               {'description': 'قیام مردم تبریز', 'is_holiday': False},
               {'description': 'روز اقتصاد مقاومتی و کارآفرینی', 'is_holiday': False}],
    },
    # اسفند
    "12": {
        '5': [{'description': 'روز بزرگداشت زمین و بانوان', 'is_holiday': False},
              {'description': 'جشن سپندارمذگان و روز عشق', 'is_holiday': False},
              {'description': 'روز بزرگداشت خواجه نصیر الدین طوسی و روز مهندس', 'is_holiday': False}],
        '7': [{'description': 'سالروز استقلال کانون وکلای دادگستری و روز وکیل مدافع', 'is_holiday': False},
              {'description': 'سالروز درگذشت علی اکبر دهخدا', 'is_holiday': False}],
        '8': [{'description': 'روز حمایت از بیماران نادر', 'is_holiday': False},
              {'description': 'روز امور تربیتی و تربیت اسلامی', 'is_holiday': False},
              {'description': 'بزرگداشت حکیم هادی سبزواری', 'is_holiday': False}],
        '9': [{'description': 'روز حمایت از حقوق مصرف‌کنندگان', 'is_holiday': False}],
        '10': [{'description': 'روز بازاریاب و مدیر فروش', 'is_holiday': False}],
        '14': [{'description': 'درگذشت دکتر محمد مصدق', 'is_holiday': False},
               {'description': 'روز احسان و نیکوکاری', 'is_holiday': False},
               {'description': 'روز ترویج فرهنگ قرض‌الحسنه', 'is_holiday': False}],
        '15': [{'description': 'روز درختکاری', 'is_holiday': False},
               {'description': 'روز آموزش همگانی حفظ محیط زیست', 'is_holiday': False}],
        '16': [{'description': 'روز کارشناس و متخصص تغذیه', 'is_holiday': False}],
        '18': [{'description': 'بزرگداشت سید جمال‌الدین اسدآبادی', 'is_holiday': False},
               {'description': 'تأسیس کانون‌های فرهنگی هنری مساجد کشور', 'is_holiday': False},
               {'description': 'روز بوشهر', 'is_holiday': False}],
        '20': [{'description': 'روز راهیان نور', 'is_holiday': False}],
        '21': [{'description': 'زادروز منصور نریمان نوازندهٔ بربط، آهنگساز، ردیف‌دان، پژوهشگر موسیقی سنتی ایران و پدر عود ایران', 'is_holiday': False},
               {'description': 'بزرگداشت نظامی گنجوی', 'is_holiday': False},
               {'description': 'روز خادمان آرامستان', 'is_holiday': False}],
        '22': [{'description': 'زادروز فرهاد فخرالدینی موسیقیدان، رهبر ارکستر ملی ایران', 'is_holiday': False},
               {'description': 'روز بزرگداشت شهدا', 'is_holiday': False},
               {'description': 'تأسیس بنیاد شهید انقلاب اسلامی', 'is_holiday': False}],
        '23': [{'description': 'روز صنعت طلا، جواهر، نقره و گوهرسنگ‌ها', 'is_holiday': False}],
        '25': [{'description': 'پایان سرایش شاهنامه', 'is_holiday': False},
               {'description': 'درگذشت علی تجویدی، نوازندهٔ ویولن و سه‌تار و آهنگساز ایرانی', 'is_holiday': False},
               {'description': 'روز بزرگداشت اختر چرخ ادب، پروین اعتصامی', 'is_holiday': False},
               {'description': 'بمباران شیمیایی حلبچه به دست ارتش بعث عراق', 'is_holiday': False}],
        '27': [{'description': 'زادروز پروین اعتصامی شاعر ایرانی', 'is_holiday': False}],
        '29': [{'description': 'روز ملی شدن صنعت نفت ایران', 'is_holiday': True}],
        '30': [{'description': 'آخرین روز سال', 'is_holiday': True}]
    }
}
