{% set name = "rokh" %}
{% set version = "0.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/openscilab/rokh
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.7
    run:
        - python >=3.7
about:
    home: https://github.com/openscilab/rokh
    license: MIT
    license_family: MIT
    summary: Rokh: Iranian Calendar Events Collection
    description: |
	    Rokh provides a unified interface for accessing Iranian calendar events across Jalali, Gregorian, and Hijri Ghamari date systems. It lets you easily retrieve national holidays, cultural events, and religious occasions by simply passing a date. It automatically converts between calendars and return event's description.
        You can use it in your apps, bots, and research tools that rely on Iranian date conversions, holidays, and cultural event data.
	
        Website: https://openscilab.com

        Repo: https://github.com/openscilab/rokh
extra:
    recipe-maintainers:
        - sepandhaghighi
